# Generated by Django 5.2.4 on 2025-09-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
    ]
