# Generated by Django 5.2.4 on 2025-09-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_delete_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.TextField(default='definir categoria'),
        ),
    ]
