# Generated by Django 5.2.4 on 2025-09-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(default='none'),
        ),
    ]
