# Generated by Django 5.2.4 on 2025-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_produto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(default=None),
        ),
    ]
