# Generated by Django 5.2.4 on 2025-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_produto_imagem_alter_produto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(default='none'),
        ),
    ]
