# Generated by Django 5.2.4 on 2025-09-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_produto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
