# Generated by Django 5.2.4 on 2025-09-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_remove_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=40)),
                ('descrição', models.TextField()),
                ('categoria', models.CharField(default='definir categoria')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
