# Generated by Django 5.2.4 on 2025-09-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_produtos_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
