# Generated by Django 5.2.4 on 2025-09-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_venda_delete_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='imagem',
        ),
    ]
