# Generated by Django 5.2.4 on 2025-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_vendas_delete_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='img', verbose_name='imagem')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('modelo', models.CharField(max_length=40, verbose_name='modelo')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('categoria', models.CharField(default='definir categoria', verbose_name='categoria')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço_unitario')),
            ],
        ),
        migrations.DeleteModel(
            name='vendas',
        ),
    ]
