# Generated by Django 5.2.4 on 2025-09-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_produtos_delete_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(default='Sem descrição', verbose_name='descrição'),
        ),
    ]
