# Generated by Django 5.2.4 on 2025-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_alter_produtos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.FileField(upload_to='img/', verbose_name='imagem'),
        ),
    ]
