# Generated by Django 5.2.4 on 2025-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.FileField(upload_to='', verbose_name='imagem'),
        ),
    ]
